### ISSUE TITLE
Integrate parinfer

### ISSUE THREAD

**Issue by arichiardi** [Lambda-X/cljs-repl-web#115]
Very cool tool, very easy to plug but probably only when we abandon `jqconsole`.

https://github.com/shaunlebron/parinfer

**Comment by tomasz-biernacki** [comment]
See https://github.com/Lambda-X/cljs-repl-web/pull/189 and https://github.com/Lambda-X/re-console/releases/tag/0.1.1

**Comment by arichiardi** [comment]
I will close this one.
