### ISSUE TITLE
Selecting code and deleting with BACKSPACE does not work

### ISSUE THREAD

**Issue by arichiardi** [Lambda-X/cljs-repl-web#171]
Same thing with DEL works, probably missing some case in key handling.

**Comment by tomasz-biernacki** [comment]
Solved by https://github.com/Lambda-X/cljs-repl-web/commit/8988c8b98d0e7ae97d02f23fae94397acd4f327c and https://github.com/Lambda-X/re-console/commit/83fdd4fefae5983bd1c71779b42a7bf0a1017929

For issues on mobile, see https://github.com/Lambda-X/cljs-repl-web/issues/196
