### ISSUE TITLE
Determine how to break evaluation

### ISSUE THREAD

**Issue by tomasz-biernacki** [Lambda-X/cljs-repl-web#182]
The form `(def a '2')` is neither evaluated nor produces an error, the cursor goes to a new line (probably it has to do with what we consider an incorrect expression and how we treat multiline)

**Comment by arichiardi** [comment]
There was an issue opened long long time ago about this, and I think the only way we have is by using modules. This way we can also I think improve the loading speed of our page.

**Comment by tomasz-biernacki** [comment]
Solved by @blackgate 's https://github.com/Lambda-X/cljs-repl-web/pull/191, thanks ;)

**Comment by arichiardi** [comment]
:+1:
