### ISSUE TITLE
After trying to require the whole browser (safari) freeze and crash ..

### ISSUE THREAD

**Issue by dstiberova** [Lambda-X/cljs-repl-web#183]
This is what happened after writing `(require '[clojure.string :as string])` into console.

<img width="1440" alt="screen shot 2016-03-23 at 18 18 49" src="https://cloud.githubusercontent.com/assets/9211809/13994261/4bdb4de8-f124-11e5-90df-918f05d932b0.png">

**Comment by arichiardi** [comment]
First of all I will try to bump replumb to the new version (and ClojureScript 1.8.34), then start investigating.
