### ISSUE TITLE
Doc does not show newlines

### ISSUE THREAD

**Issue by arichiardi** [Lambda-X/cljs-repl-web#185]
In `cljs-repl-web` we have:

```
cljs.user=> (doc clojure.string/trim)
------------------------- clojure.string/trim ([s]) Removes whitespace from both ends of string.
```

in `replumb`'s browser repl:
```
cljs.user=> (doc clojure.string/trim)
-------------------------
clojure.string/trim
([s])
  Removes whitespace from both ends of string.
```

Probably something in the CodeMirror code is removing the newlines.

**Comment by tomasz-biernacki** [comment]
Fixed by updating `re-console`, https://github.com/Lambda-X/cljs-repl-web/commit/fab4989090b2a07d41c19cc9bc7b058c549e8d4e
