### ISSUE TITLE
Strange behavior on Key UP

### ISSUE THREAD

**Issue by arichiardi** [Lambda-X/cljs-repl-web#192]
The gif explains it, I want to reach the first line with the keyboard, but I cannot do it (I try twice):

![recording_2016-04-05_114445](https://cloud.githubusercontent.com/assets/1724788/14294010/e5cce246-fb23-11e5-9678-80804d12db8f.gif)

**Comment by arichiardi** [comment]
I am going to reopen this as still something weird is going on (I am pressing only key up here):
![recording_2016-04-06_173222](https://cloud.githubusercontent.com/assets/1724788/14336914/98e6c00a-fc1d-11e5-889f-dbb6c10f8bf8.gif)

**Comment by tomasz-biernacki** [comment]
Shouldn't. 
Doesn't happen to me, try to refresh.

**Comment by arichiardi** [comment]
You are right, sorry about that, peace.
